### ISSUE TITLE
Failed to run mlx-community/c4ai-command-r-plus-4bit

### ISSUE THREAD

**Issue by Master-Lucas** [ml-explore/mlx-examples#652] opened 2024-04-05 10:41 UTC
' python -m mlx_lm.generate --model mlx-community/c4ai-command-r-plus-4bit --prompt "Write a quicksort in c++" --max-tokens 256 --use-default-chat-template ' failed to run on mlx 0.9.1 and mlx-lm 0.6.0. (M3 Max Sonama 14.4.1 64GB).
`Fetching 18 files: 100%|████████████████████| 18/18 [00:00<00:00, 134576.60it/s]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/liberoscholar/ai/envs/mlxenv/lib/python3.11/site-packages/mlx_lm/generate.py", line 148, in <module>
    main(args)
  File "/Users/liberoscholar/ai/envs/mlxenv/lib/python3.11/site-packages/mlx_lm/generate.py", line 112, in main
    model, tokenizer = load(
                       ^^^^^
  File "/Users/liberoscholar/ai/envs/mlxenv/lib/python3.11/site-packages/mlx_lm/utils.py", line 381, in load
    model = load_model(model_path, lazy)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liberoscholar/ai/envs/mlxenv/lib/python3.11/site-packages/mlx_lm/utils.py", line 345, in load_model
    model.load_weights(list(weights.items()))
  File "/Users/liberoscholar/ai/envs/mlxenv/lib/python3.11/site-packages/mlx/nn/layers/base.py", line 211, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.63.self_attn.k_norm.weight model.layers.16.self_attn.q_norm.weight model.layers.43.self_attn.k_norm.weight model.layers.53.self_attn.k_norm.weight model.layers.6.self_attn.q_norm.weight model.layers.27.self_attn.q_norm.weight model.layers.46.self_attn.q_norm.weight model.layers.20.self_attn.k_norm.weight model.layers.59.self_attn.q_norm.weight model.layers.32.self_attn.q_norm.weight model.layers.40.self_attn.k_norm.weight model.layers.20.self_attn.q_norm.weight model.layers.30.self_attn.q_norm.weight model.layers.31.self_attn.k_norm.weight model.layers.21.self_attn.k_norm.weight model.layers.15.self_attn.k_norm.weight model.layers.11.self_attn.q_norm.weight model.layers.54.self_attn.q_norm.weight model.layers.8.self_attn.k_norm.weight model.layers.52.self_attn.q_norm.weight model.layers.58.self_attn.k_norm.weight model.layers.60.self_attn.k_norm.weight model.layers.39.self_attn.q_norm.weight model.layers.56.self_attn.q_norm.weight model.layers.16.self_attn.k_norm.weight model.layers.33.self_attn.q_norm.weight model.layers.50.self_attn.q_norm.weight model.layers.10.self_attn.k_norm.weight model.layers.5.self_attn.q_norm.weight model.layers.0.self_attn.q_norm.weight model.layers.26.self_attn.k_norm.weight model.layers.10.self_attn.q_norm.weight model.layers.58.self_attn.q_norm.weight model.layers.22.self_attn.q_norm.weight model.layers.24.self_attn.k_norm.weight model.layers.57.self_attn.q_norm.weight model.layers.35.self_attn.q_norm.weight model.layers.4.self_attn.q_norm.weight model.layers.23.self_attn.q_norm.weight model.layers.57.self_attn.k_norm.weight model.layers.14.self_attn.q_norm.weight model.layers.15.self_attn.q_norm.weight model.layers.37.self_attn.q_norm.weight model.layers.17.self_attn.q_norm.weight model.layers.3.self_attn.k_norm.weight model.layers.31.self_attn.q_norm.weight model.layers.41.self_attn.q_norm.weight model.layers.44.self_attn.k_norm.weight model.layers.34.self_attn.k_norm.weight model.layers.18.self_attn.q_norm.weight model.layers.2.self_attn.k_norm.weight model.layers.0.self_attn.k_norm.weight model.layers.2.self_attn.q_norm.weight model.layers.34.self_attn.q_norm.weight model.layers.51.self_attn.q_norm.weight model.layers.8.self_attn.q_norm.weight model.layers.60.self_attn.q_norm.weight model.layers.28.self_attn.k_norm.weight model.layers.26.self_attn.q_norm.weight model.layers.45.self_attn.k_norm.weight model.layers.32.self_attn.k_norm.weight model.layers.47.self_attn.q_norm.weight model.layers.29.self_attn.q_norm.weight model.layers.52.self_attn.k_norm.weight model.layers.37.self_attn.k_norm.weight model.layers.56.self_attn.k_norm.weight model.layers.51.self_attn.k_norm.weight model.layers.46.self_attn.k_norm.weight model.layers.7.self_attn.q_norm.weight model.layers.6.self_attn.k_norm.weight model.layers.11.self_attn.k_norm.weight model.layers.48.self_attn.k_norm.weight model.layers.22.self_attn.k_norm.weight model.layers.18.self_attn.k_norm.weight model.layers.1.self_attn.k_norm.weight model.layers.29.self_attn.k_norm.weight model.layers.61.self_attn.k_norm.weight model.layers.62.self_attn.k_norm.weight model.layers.28.self_attn.q_norm.weight model.layers.4.self_attn.k_norm.weight model.layers.43.self_attn.q_norm.weight model.layers.48.self_attn.q_norm.weight model.layers.3.self_attn.q_norm.weight model.layers.13.self_attn.q_norm.weight model.layers.25.self_attn.k_norm.weight model.layers.53.self_attn.q_norm.weight model.layers.13.self_attn.k_norm.weight model.layers.33.self_attn.k_norm.weight model.layers.44.self_attn.q_norm.weight model.layers.17.self_attn.k_norm.weight model.layers.1.self_attn.q_norm.weight model.layers.24.self_attn.q_norm.weight model.layers.19.self_attn.q_norm.weight model.layers.39.self_attn.k_norm.weight model.layers.50.self_attn.k_norm.weight model.layers.42.self_attn.k_norm.weight model.layers.14.self_attn.k_norm.weight model.layers.21.self_attn.q_norm.weight model.layers.41.self_attn.k_norm.weight model.layers.7.self_attn.k_norm.weight model.layers.61.self_attn.q_norm.weight model.layers.55.self_attn.k_norm.weight model.layers.54.self_attn.k_norm.weight model.layers.30.self_attn.k_norm.weight model.layers.9.self_attn.q_norm.weight model.layers.40.self_attn.q_norm.weight model.layers.55.self_attn.q_norm.weight model.layers.36.self_attn.k_norm.weight model.layers.63.self_attn.q_norm.weight model.layers.19.self_attn.k_norm.weight model.layers.49.self_attn.k_norm.weight model.layers.45.self_attn.q_norm.weight model.layers.12.self_attn.k_norm.weight model.layers.62.self_attn.q_norm.weight model.layers.25.self_attn.q_norm.weight model.layers.23.self_attn.k_norm.weight model.layers.27.self_attn.k_norm.weight model.layers.12.self_attn.q_norm.weight model.layers.42.self_attn.q_norm.weight model.layers.35.self_attn.k_norm.weight model.layers.5.self_attn.k_norm.weight model.layers.38.self_attn.k_norm.weight model.layers.47.self_attn.k_norm.weight model.layers.36.self_attn.q_norm.weight model.layers.59.self_attn.k_norm.weight model.layers.9.self_attn.k_norm.weight model.layers.49.self_attn.q_norm.weight model.layers.38.self_attn.q_norm.weight.`
Then hanged up.

**Comment by Blaizzy** [comment] 2024-04-05 10:49
Hey @Master-Lucas 

This issue is due the PR not being merged yet.

Try installing this branch if you want to test it out: https://github.com/ml-explore/mlx-examples/tree/cohere_plus

```
pip install git+https://github.com/ml-explore/mlx-examples.git@cohere_plus#subdirectory=llms --use-pep517 
```

**Comment by Master-Lucas** [comment] 2024-04-05 16:18
Thank you very much! Blaizzy!!

I installed the branch, and did run !!
Unfortunetely my 64GB RAM is not sufficient enough for generating good speed so that I terminated when generating.

I appreciate your providing the solution.

**Comment by pharrellyhy** [comment] 2024-04-07 08:25
I can run it on my m3 max with 128GB ram but it quite slow, like 0.285 tps for prompt and 0.964 tps for generation. is it expected?

**Comment by awni** [comment] 2024-04-07 13:10
You need to set the min wired RAM on your machine to make it run reasonably fast:

`sudo sysctl iogpu.wired_lwm_mb=100000`

**Closed by awni** 2024-04-07 13:10 UTC

**Comment by pharrellyhy** [comment] 2024-04-08 06:52
not quite work. the gpu usage is low, around 30%
![Screenshot 2024-04-08 at 2 52 14 PM](https://github.com/ml-explore/mlx-examples/assets/16664753/0c1940c7-3810-4b11-bb7f-6e21fc16a015)

**Comment by lin72h** [comment] 2024-04-08 07:38
> not quite work. the gpu usage is low, around 30% ![Screenshot 2024-04-08 at 2 52 14 PM](https://private-user-images.githubusercontent.com/16664753/320380622-0c1940c7-3810-4b11-bb7f-6e21fc16a015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NjIwNDYsIm5iZiI6MTcxMjU2MTc0NiwicGF0aCI6Ii8xNjY2NDc1My8zMjAzODA2MjItMGMxOTQwYzctMzgxMC00YjExLWJiN2YtNmUyMWZjMTZhMDE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDA3MzU0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NDg3YWRjYjA0ZjBkYTliMmJhMDYxYzQyYWM1NTAxMmYyZjc1Yjc0NzM0NjBiNTAzMWZlYzIyYTdjMmRkODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1S1PPHTipxwfzoRmjuzrDDuq2pJrOO89O-gFFdcPcq8)

I think it's normal, because apple GPU doesn't support integer simdgroup matmul, so int4 doesn't utilize all the GPU ALU, and also command-r-plus model even 4bit, consume lots of memory bandwidth

**Comment by awni** [comment] 2024-04-08 13:17
@pharrellyhy what's the tokens per second? Should be around 5 for an M3 Max.

**Comment by pharrellyhy** [comment] 2024-04-08 15:44
@awni less than 1 tps for command r+ while i did get ~4 tps for dbrx.

**Comment by awni** [comment] 2024-04-08 15:47
Did you do this: `sudo sysctl iogpu.wired_lwm_mb=100000`?

**Comment by pharrellyhy** [comment] 2024-04-08 15:50
it seems it was related to the prompt i used. for a simple "hello", i got ~4.4 tps.

**Comment by pharrellyhy** [comment] 2024-04-08 15:53
my initial prompt is around 700 tokens

**Comment by pharrellyhy** [comment] 2024-04-08 15:54
> Did you do this: `sudo sysctl iogpu.wired_lwm_mb=100000`?

definitely

**Comment by awni** [comment] 2024-04-08 15:56
Interesting.. it sounds a bit like it's swapping still given how low the GPU usage is. You might also need to set the upper memory limit:

```
sudo sysctl iogpu.wired_limit_mb=120000
```

There could be some other perf bottleneck for longer prompts that we don't know about.  I'll see if I can reproduce the slowdown.

**Comment by Blaizzy** [comment] 2024-04-09 11:07
Hey @Master-Lucas and @pharrellyhy,

I wanted to check in and see if @awni's responses were helpful in resolving the issue you were facing?

**Comment by pharrellyhy** [comment] 2024-04-11 02:51
Hi, @Master-Lucas 
I think it works for dbrx, not for command r+. the generation speed for command r+ is still quite slow using same prompt as dbrx.

**Comment by voxmenthe** [comment] 2024-05-20 16:24
I get a similar error for basically 90% of the LLama-3 finetunes. I am able to convert them successfully, but they hit the same error when trying to load the model: `raise ValueError(f"Received parameters not in model: {extras}.")`

**Comment by awni** [comment] 2024-05-20 19:03
@voxmenthe could you make a new issue with steps to reproduce the problem?

**Comment by ncoder** [comment] 2024-06-30 17:19
The above branch (https://github.com/ml-explore/mlx-examples/tree/cohere_plus) gives a 404.

i'm getting a similar error
```txt
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: layers.10.feed_forward.w1.weight layers.7.feed_forward.w2.weight layers.16.feed_forward.w3.weight layers.15.feed_forward.w2.weight layers.15.feed_forward.w3.weight layers.7.feed_forward.w3.weight layers.16.attention.wk.weight layers.27.attention_norm.weight layers.18.attention.wk.weight layers.1.ffn_norm.weight layers.9.attention.wq.weight layers.24.feed_forward.w3.weight layers.8.ffn_norm.weight layers.18.feed_forward.w1.weight layers.24.feed_forward.w1.weight layers.6.feed_forward.w3.weight layers.18.attention.wq.weight layers.13.ffn_norm.weight layers.5.attention.wo.weight layers.3.attention.wv.weight layers.28.attention.wk.weight layers.10.attention.wq.weight layers.7.attention.wk.weight layers.2.feed_forward.w3.weight layers.5.attention.wq.weight layers.23.attention.wo.weight layers.15.attention.wk.weight layers.30.attention.wk.weight layers.27.attention.wq.weight layers.22.attention_norm.weight layers.14.attention.wk.weight layers.0.attention.wv.weight layers.15.feed_forward.w1.weight layers.31.attention.wq.weight layers.20.feed_forward.w3.weight layers.17.feed_forward.w2.weight layers.14.attention_norm.weight layers.8.feed_forward.w3.weight layers.4.attention_norm.weight layers.18.attention.wo.weight layers.19.attention.wo.weight layers.27.attention.wo.weight layers.30.attention_norm.weight layers.8.attention.wk.weight layers.23.attention.wk.weight layers.16.ffn_norm.weight layers.22.ffn_norm.weight layers.9.attention.wk.weight layers.19.ffn_norm.weight layers.14.attention.wv.weight layers.21.attention_norm.weight layers.18.ffn_norm.weight layers.6.attention.wq.weight layers.2.ffn_norm.weight layers.24.attention.wo.weight layers.15.attention.wq.weight layers.25.attention.wk.weight tok_embeddings.weight layers.29.feed_forward.w1.weight layers.24.attention.wv.weight layers.16.attention.wo.weight layers.11.attention_norm.weight layers.21.attention.wo.weight layers.9.feed_forward.w2.weight layers.4.attention.wv.weight layers.27.feed_forward.w2.weight layers.29.attention.wo.weight layers.1.feed_forward.w2.weight layers.28.attention.wo.weight layers.16.attention.wq.weight layers.21.attention.wq.weight layers.26.attention_norm.weight layers.7.attention.wq.weight layers.28.feed_forward.w1.weight layers.21.feed_forward.w2.weight layers.2.attention.wo.weight layers.26.ffn_norm.weight layers.12.attention.wk.weight layers.27.feed_forward.w1.weight layers.27.attention.wv.weight layers.18.attention.wv.weight layers.23.attention.wq.weight layers.20.attention.wv.weight layers.8.feed_forward.w2.weight layers.2.attention.wq.weight layers.31.feed_forward.w1.weight layers.7.attention.wo.weight layers.20.attention.wq.weight layers.13.feed_forward.w2.weight layers.11.attention.wo.weight layers.26.attention.wo.weight layers.27.attention.wk.weight layers.13.attention_norm.weight layers.10.attention.wo.weight layers.10.attention.wv.weight layers.20.attention_norm.weight layers.3.feed_forward.w3.weight layers.23.feed_forward.w2.weight layers.0.attention.wq.weight layers.10.feed_forward.w3.weight layers.25.attention.wo.weight layers.12.ffn_norm.weight layers.16.attention_norm.weight layers.22.feed_forward.w3.weight layers.23.attention_norm.weight layers.25.feed_forward.w3.weight layers.11.attention.wv.weight layers.25.feed_forward.w1.weight layers.1.feed_forward.w3.weight layers.2.attention.wk.weight layers.17.feed_forward.w3.weight layers.7.ffn_norm.weight layers.18.attention_norm.weight layers.19.feed_forward.w3.weight layers.17.ffn_norm.weight layers.30.ffn_norm.weight layers.14.feed_forward.w1.weight layers.6.attention.wk.weight layers.9.feed_forward.w1.weight layers.5.attention.wk.weight layers.23.attention.wv.weight layers.24.attention.wq.weight layers.0.feed_forward.w3.weight layers.28.ffn_norm.weight layers.29.attention.wv.weight layers.10.attention.wk.weight layers.3.feed_forward.w1.weight layers.8.attention.wo.weight layers.11.attention.wq.weight layers.11.attention.wk.weight layers.7.feed_forward.w1.weight layers.1.attention.wq.weight layers.9.attention.wv.weight norm.weight layers.29.attention_norm.weight layers.26.feed_forward.w1.weight layers.25.attention.wq.weight layers.17.feed_forward.w1.weight layers.12.attention_norm.weight layers.14.ffn_norm.weight layers.8.attention.wq.weight layers.15.attention_norm.weight layers.2.attention.wv.weight layers.0.attention.wo.weight layers.9.ffn_norm.weight layers.0.feed_forward.w1.weight layers.19.attention.wv.weight layers.9.feed_forward.w3.weight layers.22.attention.wk.weight layers.22.feed_forward.w2.weight layers.20.feed_forward.w2.weight layers.24.feed_forward.w2.weight layers.20.attention.wo.weight layers.30.attention.wv.weight layers.25.attention_norm.weight layers.19.attention_norm.weight layers.31.attention.wo.weight layers.15.attention.wv.weight layers.14.attention.wo.weight layers.31.feed_forward.w2.weight layers.31.attention_norm.weight layers.13.attention.wo.weight layers.12.feed_forward.w1.weight layers.2.feed_forward.w1.weight layers.5.feed_forward.w3.weight layers.11.feed_forward.w3.weight layers.16.feed_forward.w1.weight layers.3.ffn_norm.weight layers.13.attention.wv.weight layers.26.attention.wq.weight layers.21.attention.wk.weight layers.30.attention.wq.weight layers.0.attention.wk.weight layers.18.feed_forward.w3.weight layers.15.attention.wo.weight layers.14.feed_forward.w2.weight layers.4.ffn_norm.weight layers.31.feed_forward.w3.weight layers.17.attention.wo.weight layers.4.feed_forward.w1.weight layers.7.attention_norm.weight layers.0.ffn_norm.weight layers.28.feed_forward.w2.weight layers.5.feed_forward.w2.weight layers.5.attention_norm.weight layers.0.feed_forward.w2.weight layers.17.attention.wk.weight layers.26.attention.wk.weight layers.18.feed_forward.w2.weight layers.5.ffn_norm.weight layers.6.attention.wo.weight layers.17.attention_norm.weight layers.12.attention.wv.weight layers.1.feed_forward.w1.weight layers.20.attention.wk.weight layers.6.attention.wv.weight layers.22.attention.wo.weight layers.11.feed_forward.w2.weight output.weight layers.19.attention.wq.weight layers.22.feed_forward.w1.weight layers.27.feed_forward.w3.weight layers.5.feed_forward.w1.weight layers.23.feed_forward.w1.weight layers.13.attention.wq.weight layers.26.feed_forward.w3.weight layers.15.ffn_norm.weight layers.21.feed_forward.w3.weight layers.29.feed_forward.w3.weight layers.26.feed_forward.w2.weight layers.11.feed_forward.w1.weight layers.24.attention_norm.weight layers.19.feed_forward.w1.weight layers.21.attention.wv.weight layers.6.feed_forward.w2.weight layers.31.attention.wv.weight layers.29.feed_forward.w2.weight layers.12.attention.wq.weight layers.6.ffn_norm.weight layers.25.attention.wv.weight layers.24.attention.wk.weight layers.29.ffn_norm.weight layers.23.ffn_norm.weight layers.9.attention_norm.weight layers.28.feed_forward.w3.weight layers.3.feed_forward.w2.weight layers.10.attention_norm.weight layers.13.feed_forward.w1.weight layers.30.attention.wo.weight layers.11.ffn_norm.weight layers.4.attention.wq.weight layers.1.attention.wv.weight layers.14.attention.wq.weight layers.16.attention.wv.weight layers.4.feed_forward.w2.weight layers.1.attention.wk.weight layers.17.attention.wq.weight layers.26.attention.wv.weight layers.22.attention.wv.weight layers.22.attention.wq.weight layers.13.attention.wk.weight layers.13.feed_forward.w3.weight layers.0.attention_norm.weight layers.14.feed_forward.w3.weight layers.25.feed_forward.w2.weight layers.17.attention.wv.weight layers.9.attention.wo.weight layers.24.ffn_norm.weight layers.5.attention.wv.weight layers.8.feed_forward.w1.weight layers.20.ffn_norm.weight layers.4.attention.wk.weight layers.12.feed_forward.w2.weight layers.1.attention_norm.weight layers.16.feed_forward.w2.weight layers.28.attention.wq.weight layers.3.attention.wo.weight layers.28.attention.wv.weight layers.30.feed_forward.w2.weight layers.19.feed_forward.w2.weight layers.21.ffn_norm.weight layers.3.attention.wk.weight layers.8.attention.wv.weight layers.8.attention_norm.weight layers.1.attention.wo.weight layers.23.feed_forward.w3.weight layers.10.ffn_norm.weight layers.3.attention_norm.weight layers.7.attention.wv.weight layers.27.ffn_norm.weight layers.4.feed_forward.w3.weight layers.21.feed_forward.w1.weight layers.6.feed_forward.w1.weight layers.29.attention.wq.weight layers.30.feed_forward.w3.weight layers.2.feed_forward.w2.weight layers.28.attention_norm.weight layers.4.attention.wo.weight layers.29.attention.wk.weight layers.25.ffn_norm.weight layers.2.attention_norm.weight layers.6.attention_norm.weight layers.12.feed_forward.w3.weight layers.12.attention.wo.weight layers.19.attention.wk.weight layers.31.attention.wk.weight layers.30.feed_forward.w1.weight layers.20.feed_forward.w1.weight layers.3.attention.wq.weight layers.10.feed_forward.w2.weight layers.31.ffn_norm.weight.

```

Having a reference to the prior fix, even if not the same, would be helpful to understand what's missing and how to fix it.

**Comment by awni** [comment] 2024-07-03 15:07
@ncoder you should use MLX LM to run Mistral v0.3. It should work out of the box.

Docs: https://github.com/ml-explore/mlx-examples/blob/main/llms/README.md

Here's how to do it:

1. Install: `pip install -U mlx_lm`
2. Example command: `mlx_lm.generate --model mlx-community/Mistral-7B-Instruct-v0.3-4bit --prompt "Hello!" --max-tokens 128 --temp 0.0`
