### ISSUE TITLE
[llama] Using precomputed weights from mlx-llama no longer works.

### ISSUE THREAD

**Issue by dastrobu** [ml-explore/mlx-examples#101] opened 2023-12-14 10:44 UTC
I think f0c57c1361b4084976f4e39df3a6bc82d44ef40d
broke the example of using the precomputed weights from [mlx-llama](https://huggingface.co/mlx-llama) as these precomputed weights come in the wrong file name convention: expected `weights.npz`, actual `Llama-2-7b-chat.npz`. 
This can be easily fixed by symlinking: `ln -s Llama-2-7b-chat.npz  weights.npz`. However, `llama.py` now expects that there is a `params.json`, which does not exist for the precomputed weights. 

So I'd suggest to either update the [mlx-llama](https://huggingface.co/mlx-llama) repo or simply remove the following paragraph from the README.md. 

> Alternatively, you can also download a select converted checkpoints from the
[mlx-llama](https://huggingface.co/mlx-llama) community organisation on Hugging
Face and skip the conversion step.

I successfully ran the llama example with precomputed weights prior to f0c57c1361b4084976f4e39df3a6bc82d44ef40d.

Converting weights from the ai.meta.com model still works as documented.

**Comment by awni** [comment] 2023-12-15 04:11
Dupe of #65 will fix. Intention is to update the HF repo.

**Closed by awni** 2023-12-15 04:11 UTC
