### ISSUE TITLE
When loading an adapter in mlx_lm, the rank, alpha and dropout are not loaded to what was trained with

### ISSUE THREAD

**Issue by ryanmitts** [ml-explore/mlx-examples#622] opened 2024-03-26 09:48 UTC
I'm not too sure if this is a problem, but when when looking through the LoRA example, it looks like when you load an adapter file back, it doesn't make sure to create the LoRALinear layers with the [same arguments](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/tuner/utils.py#L94) that were used to train.

Do these values need to be saved in a metadata file alongsize the adapters.npz file and loaded back with it?

**Comment by mzbac** [comment] 2024-03-26 10:07
The Lora adapters' weight contains information about the `r` and `alpha`, so it can be recovered by loading the weight into the Lora layer. However, I think that if a user does not use the default scale, this may cause issues when applying the Lora layer as that information is not saved anywhere. I am not sure if simply changing the scale to an mx array which will be saved as part of the Lora adapter would fix this issue or if we have to do something else to save the scale value somewhere so we can recover it when loading the adapter. @awni

**Comment by rshah918** [comment] 2024-03-27 03:31
@awni Hey, my fine tuning is disappearing after fusing. Maybe its because I set a higher scale during training but not during fusing? 

How can I configure the scale for fusing? You previously linked me to the [examples directory ](https://github.com/ml-explore/mlx-examples/blob/297a908e3db205a5d35acf806a30addbb2515788/llms/mlx_lm/examples/lora_config.yaml#L61C3-L61C14)
but seems like thats just a demo config file thats not being used by fuse.py.

**Comment by awni** [comment] 2024-03-27 03:46
There is a WIP PR for solving exactly that problem #623 

At the moment, if you change the scale through the config indeed it will not be reflected when you then reload the adapters.. that was an oversight when we made that parameter configurable. You can temporarily fix it by editing the scale here https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/tuner/lora.py#L16

**Comment by rshah918** [comment] 2024-03-27 21:24
@awni Awesome, thank you! The issue persists even when setting scale=7000. Confirmed that the pre-fused model works well. Will continue to try even larger values and report back what I observe

**Comment by rshah918** [comment] 2024-03-27 21:40
Tried scale=999999999999999.0 yet no effect on fused model output. Fusing with the command 
`python3 -m mlx_lm.fuse --model mlx_model_q --adapter-file adapters.npz --de-quantize`

**Comment by rshah918** [comment] 2024-03-29 16:28
@awni Any pointers on why increasing the scale [here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/tuner/lora.py#L16) still results in fine tuning getting erased (am i doing something wrong)? Or is the resolution also part of that WIP PR?

**Comment by rshah918** [comment] 2024-03-29 16:47
Wait!!! Okay I manually changed the scale in lora/models.py [here](https://github.com/ml-explore/mlx-examples/blob/b80adbcc3ee5b00ad43432faede408b983f152c2/lora/models.py#L113C9-L113C27)  and then ran `python3 fuse.py --model mlx_model --adapter-file adapters.npz` Finally, I dragged the lora_fused_model into llms/mlx_lm and ran the server. Fused model is working great!!

**Comment by mzbac** [comment] 2024-03-29 22:54
That's the issue when loading Lora weight - the scaling value gets lost because it wasn't saved anywhere. Another way to temporarily fix this is to update [here](https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/tuner/lora.py#L13-L16) to match your configuration during fuse.

**Comment by awni** [comment] 2024-04-02 20:55
This should be fixed in main and just released MLX LM (`pip install -U mlx-lm`).

**Closed** 2024-04-02 20:57 UTC
