### ISSUE TITLE
Mnist example run error

### ISSUE THREAD

**Issue by zbml** [ml-explore/mlx-examples#487] opened 2024-02-26 06:55 UTC
When I am using:
python main.py
it give error like:
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
libc++abi: terminating due to uncaught exception of type std::runtime_error: [Compile::eval_cpu] Failed to compile function BroadcastSubtractExp_VV_f4f4_11160318154034397263_strided_2 with error code 256.

But when i run using:
python main.py --gpu
it works ok.

So Is this code can only run on gpu?

I use M3 max, python 3.11.7 and MLX 0.4.0

**Comment by haoliplus** [comment] 2024-02-26 08:16
The same error occurs after I upgrade to 0.4(M2 Pro ,python 3.10). Rolling back to 0.3 fixes this problem. Can anyone fix this in version 0.4?

(By the way, other models also have the same error, like stable diffusion.)

**Comment by awni** [comment] 2024-02-26 14:10
Could you share the output of `clang --version` ?

E.g. something like:
```
(base) ~ % clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by zbml** [comment] 2024-02-27 01:30
> Could you share the output of `clang --version` ?
> 
> E.g. something like:
> 
> ```
> (base) ~ % clang --version
> Apple clang version 15.0.0 (clang-1500.1.0.2.5)
> Target: arm64-apple-darwin23.2.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> ```

Below is my output:

```
(base) ➜  ~ clang --version
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: arm64-apple-darwin23.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by awni** [comment] 2024-02-27 01:32
Could you also share more of the error output when you tried to run the mnist example on the CPU?

**Comment by zbml** [comment] 2024-02-27 01:59
This is all I got:

```
(base) ➜  mlxMNIST git:(main) ✗ python main.py
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:33:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/machine/_types.h:34:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/arm/_types.h:57:3: error: typedef redefinition with different types ('union __mbstate_t' vs 'union __mbstate_t')
} __mbstate_t;
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/arm/_types.h:57:3: note: previous definition is here
} __mbstate_t;
  ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:57:8: error: redefinition of '__darwin_pthread_handler_rec'
struct __darwin_pthread_handler_rec {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:57:8: note: previous definition is here
struct __darwin_pthread_handler_rec {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:63:8: error: redefinition of '_opaque_pthread_attr_t'
struct _opaque_pthread_attr_t {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:63:8: note: previous definition is here
struct _opaque_pthread_attr_t {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:68:8: error: redefinition of '_opaque_pthread_cond_t'
struct _opaque_pthread_cond_t {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:68:8: note: previous definition is here
struct _opaque_pthread_cond_t {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:73:8: error: redefinition of '_opaque_pthread_condattr_t'
struct _opaque_pthread_condattr_t {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:73:8: note: previous definition is here
struct _opaque_pthread_condattr_t {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:78:8: error: redefinition of '_opaque_pthread_mutex_t'
struct _opaque_pthread_mutex_t {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:78:8: note: previous definition is here
struct _opaque_pthread_mutex_t {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:83:8: error: redefinition of '_opaque_pthread_mutexattr_t'
struct _opaque_pthread_mutexattr_t {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:83:8: note: previous definition is here
struct _opaque_pthread_mutexattr_t {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:88:8: error: redefinition of '_opaque_pthread_once_t'
struct _opaque_pthread_once_t {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:88:8: note: previous definition is here
struct _opaque_pthread_once_t {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:93:8: error: redefinition of '_opaque_pthread_rwlock_t'
struct _opaque_pthread_rwlock_t {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:93:8: note: previous definition is here
struct _opaque_pthread_rwlock_t {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:98:8: error: redefinition of '_opaque_pthread_rwlockattr_t'
struct _opaque_pthread_rwlockattr_t {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:98:8: note: previous definition is here
struct _opaque_pthread_rwlockattr_t {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/arm_fp16.h:27:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/stdint.h:124:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/lib/clang/16/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_types.h:80:
/Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/_pthread/_pthread_types.h:103:8: error: redefinition of '_opaque_pthread_t'
struct _opaque_pthread_t {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_pthread/_pthread_types.h:103:8: note: previous definition is here
struct _opaque_pthread_t {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:30:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/bf16.h:5:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/algorithm:1708:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__debug:15:
/Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/is_constant_evaluated.h:28:6: error: redefinition of '__libcpp_is_constant_evaluated'
bool __libcpp_is_constant_evaluated() noexcept { return __builtin_is_constant_evaluated(); }
     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/is_constant_evaluated.h:28:6: note: previous definition is here
bool __libcpp_is_constant_evaluated() _NOEXCEPT { return __builtin_is_constant_evaluated(); }
     ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:30:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/bf16.h:5:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/algorithm:1708:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__debug:16:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/cstddef:38:
/Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/enable_if.h:20:90: error: redefinition of 'enable_if'
template <bool, class _Tp = void> struct __attribute__((__type_visibility__("default"))) enable_if {};
                                                                                         ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/enable_if.h:20:63: note: previous definition is here
template <bool, class _Tp = void> struct _LIBCPP_TEMPLATE_VIS enable_if {};
                                                              ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:30:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/bf16.h:5:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/algorithm:1708:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__debug:16:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/cstddef:38:
/Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/enable_if.h:21:77: error: redefinition of 'enable_if<true, _Tp>'
template <class _Tp> struct __attribute__((__type_visibility__("default"))) enable_if<true, _Tp> {typedef _Tp type;};
                                                                            ^~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/enable_if.h:21:50: note: previous definition is here
template <class _Tp> struct _LIBCPP_TEMPLATE_VIS enable_if<true, _Tp> {typedef _Tp type;};
                                                 ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:30:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/bf16.h:5:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/algorithm:1708:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__debug:16:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/cstddef:38:
/Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/enable_if.h:23:33: error: template parameter redefines default argument
template <bool _Bp, class _Tp = void> using __enable_if_t __attribute__((__nodebug__)) = typename enable_if<_Bp, _Tp>::type;
                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/enable_if.h:23:33: note: previous default template argument defined here
template <bool _Bp, class _Tp = void> using __enable_if_t _LIBCPP_NODEBUG = typename enable_if<_Bp, _Tp>::type;
                                ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:30:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/bf16.h:5:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/algorithm:1708:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__debug:16:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/cstddef:38:
/Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/enable_if.h:26:33: error: template parameter redefines default argument
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
                                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/enable_if.h:26:33: note: previous default template argument defined here
template <bool _Bp, class _Tp = void> using enable_if_t = typename enable_if<_Bp, _Tp>::type;
                                ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:30:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/bf16.h:5:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/algorithm:1708:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__debug:16:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/cstddef:39:
/Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/integral_constant.h:21:56: error: redefinition of 'integral_constant'
struct __attribute__((__type_visibility__("default"))) integral_constant
                                                       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/integral_constant.h:21:29: note: previous definition is here
struct _LIBCPP_TEMPLATE_VIS integral_constant
                            ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:30:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/bf16.h:5:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/algorithm:1708:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__debug:16:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/cstddef:40:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/is_integral.h:14:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/remove_cv.h:13:
/Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/remove_const.h:22:8: error: redefinition of 'remove_const'
struct remove_const {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/remove_const.h:22:8: note: previous definition is here
struct remove_const {
       ^
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/backend/common/compiled_preamble.h:6:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/half_types.h:30:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/work/mlx/types/bf16.h:5:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/algorithm:1708:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__debug:16:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/cstddef:40:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/is_integral.h:14:
In file included from /Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/remove_cv.h:14:
/Users/runner/miniforge3/conda-bld/mlx_1708685518110/_build_env/bin/../include/c++/v1/__type_traits/remove_volatile.h:22:8: error: redefinition of 'remove_volatile'
struct remove_volatile {
       ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1/__type_traits/remove_volatile.h:22:8: note: previous definition is here
struct remove_volatile {
       ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
libc++abi: terminating due to uncaught exception of type std::runtime_error: [Compile::eval_cpu] Failed to compile function BroadcastSubtractExp_VV_f4f4_11160318154034397263_strided_2 with error code 256.

[1]    35010 abort      python main.py
```

**Comment by awni** [comment] 2024-02-27 04:00
It looks like you are on MacOS 13.3. I wonder if that's the issue 🤔 . The compiler version looks good. If you are interested in trying it with MacOS 14+ that would be great. I'd love to know if that fixes the problem. In the meantime see if I can reproduce on an older OS.

**Comment by zbml** [comment] 2024-02-27 06:10
> It looks like you are on MacOS 13.3. I wonder if that's the issue 🤔 . The compiler version looks good. If you are interested in trying it with MacOS 14+ that would be great. I'd love to know if that fixes the problem. In the meantime see if I can reproduce on an older OS.

Actually, I use the newest MacOS 14.3.1

**Comment by awni** [comment] 2024-02-27 06:16
Hmm, I see. Maybe it's just using an old Xcode:
```
In file included from /Applications/Xcode_15.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdint.h:52:
```

Try:

```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
```

**Comment by awni** [comment] 2024-02-27 06:18
Also I think this should be fixed in after merging https://github.com/ml-explore/mlx/pull/747/files

**Closed** 2024-02-27 06:20 UTC

**Comment by zbml** [comment] 2024-02-27 06:23
I did this
```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
```

Still got same error.

Will wait for new version

> Also I think this should be fixed in after merging https://github.com/ml-explore/mlx/pull/747/files

And one more question, after do this:
```
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
```
Is there any side effect? Or anything i can do to rollback this?

**Comment by awni** [comment] 2024-02-27 14:11
> Is there any side effect? Or anything i can do to rollback this?

It will use the newer version of Xcode which is usually what you want so I recommend you keep it. But you can switch back

```
sudo xcode-select --switch /Library/Developer/
```

**Comment by zbml** [comment] 2024-02-28 01:20
> > Is there any side effect? Or anything i can do to rollback this?
> 
> It will use the newer version of Xcode which is usually what you want so I recommend you keep it. But you can switch back
> 
> ```
> sudo xcode-select --switch /Library/Developer/
> ```

Thanks
