### ISSUE TITLE
Add support for llava-hf/llava-v1.6-mistral-7b-hf

### ISSUE THREAD

**Issue by katopz** [ml-explore/mlx-examples#638] opened 2024-03-30 12:54 UTC
Currently we are not support `llava-hf/llava-v1.6-mistral-7b-hf`
```
ValueError: Model type mistral not supported. Currently only 'llama' is supported
```

It would be nice if we support this one.

**Comment by jrp2014** [comment] 2024-03-30 22:54
See #605

**Comment by awni** [comment] 2024-04-04 22:39
Let's close this in favor of #605.

**Closed by awni** 2024-04-04 22:39 UTC

**Comment by okpatil4u** [comment] 2024-05-09 14:46
```
python generate.py \
  --model llava-hf/llava-v1.6-mistral-7b-hf \
  --image "/Users/omkarpatil/Downloads/maxresdefault.jpg " \
  --prompt "USER: <image>\nWhat is this image about ?\nASSISTANT:" \
  --max-tokens 128 \
  --temp 0

ValueError: Model type mistral not supported. Currently only 'llama' is supported
```

I don't think that the issue is resolved. I am using May 8 commit[fad959837232b0b4deeaa29b147dc69cbc9c5d19].

**Comment by awni** [comment] 2024-05-11 13:25
I don't think we ever added it. But you should checkout out MLX VLM by @Blaizzy : https://github.com/Blaizzy/mlx-vlm

**Comment by Blaizzy** [comment] 2024-05-11 13:37
Thanks for the shoutout @awni!

@katopz we are extending support for all vlms,

Currently we support llava, idefics 2, nanollava with many more coming such as QwenVL, bunny, internVL, including llava-next which that model is based on.

If you are interested you can send us a PR, I will be there to help if needed :)
