### ISSUE TITLE
mlx 0.13 very slow with q8 and fp16

### ISSUE THREAD

**Issue by ivanfioravanti** [ml-explore/mlx-examples#776] opened 2024-05-11 22:20 UTC
I was testing the new quantize by @angeloskath with some Italian prompts that were failing with previous version and now are PERFECT! But while doing this I have seen extreme slowness with q8 and fp16 version.

I'm using meta-llama/Meta-Llama-3-70B-Instruct for test on M2 Ultra 192GB.

I created 3 conversions of it with:
```
mlx_lm.convert --hf-path meta-llama/Meta-Llama-3-70B-Instruct -q --q-bits 4 --mlx-path mlx_model_q4
mlx_lm.convert --hf-path meta-llama/Meta-Llama-3-70B-Instruct -q --q-bits 8 --mlx-path mlx_model_q8
mlx_lm.convert --hf-path meta-llama/Meta-Llama-3-70B-Instruct --mlx-path mlx_model_fp16
```

Then I tested generation with:
```
mlx_lm.generate --prompt "Write the story of Albert Einstein" --model mlx_model_q4
mlx_lm.generate --prompt "Write the story of Albert Einstein" --model mlx_model_q8
mlx_lm.generate --prompt "Write the story of Albert Einstein" --model mlx_model_fp16
```

q4 14.9 t/s (GPU >1300Mhz 115W)
q8 & fp16 0.4 t/s  (GPU <1100Mhz peak 2W)

**Comment by ivanfioravanti** [comment] 2024-05-12 20:15
I tested on M3 Max and got same result. with even lower power consumption and GPU frequency. Really strange.

**Comment by awni** [comment] 2024-05-13 23:30
It's pretty slow for me also in 8-bit (and presumably 16 as well, but didn't test).

**Comment by awni** [comment] 2024-05-13 23:43
@ivanfioravanti just curious you phrased this issue as if it used to be faster in previous MLX versions. Is that the case?

**Comment by ivanfioravanti** [comment] 2024-05-18 19:38
Sorry for the delay I was out the whole week and happy to be back playing with MLX 🛝
I thought the issue was impacting all models using q8 but this is not the case. It seems issue is present with Llama 70B only.

- Mistral-7B-Instruct-v0.2 works like a charm
- mlx-community/dolphin-2.9.1-yi-1.5-34b-8bit works like a charm

Can this be related to model size? 70B? I will try comparing another large model.

**Comment by awni** [comment] 2024-05-20 13:57
> Can this be related to model size? 70B? 

Oh yes, it's almost certainly related to the size / amount of RAM required. There seems to be a performance cliff for very large models. It shouldn't be swapping because its still not using all the RAM on the machine but it does seem related to memory page demand. Still debugging.. this one might take a little while to iron out.

**Comment by fengpings** [comment] 2024-07-03 01:57
Same problem with 'Qwen2-57B-A14B-Instruct' and 'Qwen2-72B-Instruct' here! 

- q8 runs significantly slower than q4
- GPU utilization of q8 is low
- using mlx==0.15.2 on M3 Max 128GB.

**Comment by awni** [comment] 2024-07-03 13:57
Have you tried setting your memory limits, e.g. `iogpu.wired_lwm_mb` and `iogpu.wired_limit_mb` ?

**Comment by fengpings** [comment] 2024-07-06 05:42
> Have you tried setting your memory limits, e.g. `iogpu.wired_lwm_mb` and `iogpu.wired_limit_mb` ?

Sorry for the late reply! I tried to set both `iogpu.wired_lwm_mb` and `iogpu.wird_limit_mb` to 100GB:
`sudo sysctl iogpu.wired_limit_mb=102400` and `sudo sysctl iogpu.wired_lwm_mb=102400`

but the generation speeds for 'Qwen2-57B-A14B-Instruct' and 'Qwen2-72B-Instruct'  are still slow.

**Comment by awni** [comment] 2024-07-06 17:58
One thing that might help is to restart your machine. This isn't a permanent fix.. but it would be interesting to know if getting your machine out of some fragmented state could help here.

Also to be sure, we are talking about the 8-bit models right?  So for Qwen 72B that should be about 80GB or so?

**Comment by fengpings** [comment] 2024-07-07 06:39
> One thing that might help is to restart your machine. This isn't a permanent fix.. but it would be interesting to know if getting your machine out of some fragmented state could help here.
> 
> Also to be sure, we are talking about the 8-bit models right? So for Qwen 72B that should be about 80GB or so?

1. Restart helps! Generation speed of the 8-bit models back to normal
2. Yes, we are talking about 8-bit models
3. 'Qwen2-57B-A14B-Instruct' around 60GB in mem, 'Qwen2-72B-Instruct' around 77GB in mem

**Comment by awni** [comment] 2024-07-07 13:12
> Restart helps!

Since that helped it suggests its related to some system-level fragmentation issues we've noticed before. As I said, we don't have a good fix for that yet :\. Upgrading to Sequoia (macOS 15.0) may also help in this case, but I haven't confirmed that yet.

**Comment by fengpings** [comment] 2024-07-08 01:47
> Upgrading to Sequoia (macOS 15.0)

I'll have a try, many thanks!

**Comment by awni** [comment] 2024-11-01 18:04
This should be resolved in the latest MLX + the next release of MLX LM. See the [documentation here](https://github.com/ml-explore/mlx-examples/tree/main/llms#large-models). Note it requires OS 15.0 or higher.

**Closed by awni** 2024-11-01 18:04 UTC
