### ISSUE TITLE
Error in finetuning mistralai/Mixtral-8x7B-v0.1 using mlx_lm.lora

### ISSUE THREAD

**Issue by Satyam7166-tech** [ml-explore/mlx-examples#607] opened 2024-03-22 11:21 UTC
Hello,

I am using the latest verson of this repo to avoid issues (just cloned now). Here is the command I'm running.

>  python -m mlx_lm.lora \
  --train \
  --model mistralai/Mixtral-8x7B-v0.1\
  --data /Users/macstudiosct/projects/finetune_mlx/finetuning_data/data \
  --batch-size 3 \
  --lora-layers 20 \
  --iters 5000 --max-seq-length 4096

And here is the trace of the error:

`Loading pretrained model
Fetching 26 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [00:00<00:00, 69860.28it/s]
Trainable parameters: 0.006% (2.787M/46702.793M)
Loading datasets
Training
Starting training..., iters: 5000
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/macstudiosct/projects/finetune_mlx/updated_4.mlx_examples/mlx-examples/llms/mlx_lm/lora.py", line 257, in <module>
    run(types.SimpleNamespace(**args))
  File "/Users/macstudiosct/projects/finetune_mlx/updated_4.mlx_examples/mlx-examples/llms/mlx_lm/lora.py", line 204, in run
    train(
  File "/Users/macstudiosct/projects/finetune_mlx/updated_4.mlx_examples/mlx-examples/llms/mlx_lm/tuner/trainer.py", line 219, in train
    lvalue, toks = step(batch)
  File "/Users/macstudiosct/projects/finetune_mlx/updated_4.mlx_examples/mlx-examples/llms/mlx_lm/tuner/trainer.py", line 195, in step
    (lvalue, toks), grad = loss_value_and_grad(model, *batch)
  File "/Users/macstudiosct/projects/finetune_mlx/mlx1/lib/python3.10/site-packages/mlx/nn/utils.py", line 34, in wrapped_value_grad_fn
    value, grad = value_grad_fn(model.trainable_parameters(), *args, **kwargs)
  File "/Users/macstudiosct/projects/finetune_mlx/mlx1/lib/python3.10/site-packages/mlx/nn/utils.py", line 28, in inner_fn
    return fn(*args, **kwargs)
  File "/Users/macstudiosct/projects/finetune_mlx/updated_4.mlx_examples/mlx-examples/llms/mlx_lm/tuner/trainer.py", line 67, in default_loss
    logits, _ = model(inputs)
  File "/Users/macstudiosct/projects/finetune_mlx/updated_4.mlx_examples/mlx-examples/llms/mlx_lm/models/mixtral.py", line 238, in __call__
    out, cache = self.model(inputs, cache)
  File "/Users/macstudiosct/projects/finetune_mlx/updated_4.mlx_examples/mlx-examples/llms/mlx_lm/models/mixtral.py", line 221, in __call__
    h, cache[e] = layer(h, mask, cache[e])
  File "/Users/macstudiosct/projects/finetune_mlx/updated_4.mlx_examples/mlx-examples/llms/mlx_lm/models/mixtral.py", line 187, in __call__
    r = self.block_sparse_moe(self.post_attention_layernorm(h))
  File "/Users/macstudiosct/projects/finetune_mlx/updated_4.mlx_examples/mlx-examples/llms/mlx_lm/models/mixtral.py", line 147, in __call__
    mx.eval(inds)
ValueError: [eval] Attempting to eval an array without a primitive.`

I have also tried the same command with mistral and other models, it works. Only mixtral causes trouble.

Thanks for your time.

**Comment by mzbac** [comment] 2024-03-22 11:53
There is an issue compiling the model during the training step. Before it gets fixed, you can manually delete this line in the Lora trainer: https://github.com/ml-explore/mlx-examples/blob/main/llms/mlx_lm/tuner/trainer.py#L192
cc @awni

**Comment by Satyam7166-tech** [comment] 2024-03-22 12:00
Thanks, it works now :)

**Comment by l0d0v1c** [comment] 2024-03-23 07:36
Line 192 removal does not work for me
```
Loading pretrained model
Trainable parameters: 0.005% (2.229M/46702.793M)
Loading datasets
Training
Starting training..., iters: 1000
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/pro/mambaforge/envs/torch/lib/python3.11/site-packages/mlx_lm/lora.py", line 257, in <module>
    run(types.SimpleNamespace(**args))
  File "/Users/pro/mambaforge/envs/torch/lib/python3.11/site-packages/mlx_lm/lora.py", line 204, in run
    train(
  File "/Users/pro/mambaforge/envs/torch/lib/python3.11/site-packages/mlx_lm/tuner/trainer.py", line 219, in train
    lvalue, toks = step(batch)
                   ^^^^^^^^^^^
  File "/Users/pro/mambaforge/envs/torch/lib/python3.11/site-packages/mlx_lm/tuner/trainer.py", line 195, in step
    (lvalue, toks), grad = loss_value_and_grad(model, *batch)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pro/mambaforge/envs/torch/lib/python3.11/site-packages/mlx/nn/utils.py", line 34, in wrapped_value_grad_fn
    value, grad = value_grad_fn(model.trainable_parameters(), *args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [reshape] Cannot reshape array of size 32 into shape (32,4096).
```

**Comment by awni** [comment] 2024-03-23 14:21
Very odd.. I'm unable to reproduce that problem. Which version of MLX are you using? Which version of MLX LM?

**Comment by l0d0v1c** [comment] 2024-03-23 14:30
mlx 0.8.0 mlx LM 0.4.0 . Got the same error as @Satyam7166-tech . This one is after line 192 fixing proposed by @mzbac

**Comment by awni** [comment] 2024-03-23 14:32
Could you share the command?

**Comment by l0d0v1c** [comment] 2024-03-23 16:26
python -m mlx_lm.lora --model ./mixtral4b-mlx-instruct --adapter-file adapters-plucv3.npz --data ./datapluc --batch-size 2 --train --iters 1000 --lora-layers 16

**Comment by awni** [comment] 2024-03-23 22:23
I see.. I think this was actually from the bug [here](https://github.com/ml-explore/mlx/pull/879) that was introduced in 0.8 and just fixed.

Sorry about that. You can revert to 0.7 (or build MLX from source) until we have a patch release / 0.9 is out.

**Comment by awni** [comment] 2024-03-23 22:25
I'm going to close this issue because we landed the compile fix. Everything is working on main so it will be a few days at most until this percolates into our relese. 

Sorry for the noise here.. we're working on some regression testing for this model to keep us honest.

**Closed** 2024-03-23 22:25 UTC

**Comment by awni** [comment] 2024-03-25 04:10
This should work now with the latest MLX, if you do `pip install -U mlx`.
